### PR TITLE
Implement Slack notification of build failure

### PR DESCRIPTION
**Pull request by giorgiosironi**
For https://github.com/elifesciences/elife-xpub/issues/1543

- Add Notification class
- Add branch between email and Slack notifications
- Expand elifeSlack to allow specifying the channel
- Implement Slack notification in elifePipeline() step

### CODE REVIEW

**Comment by GiancarloFusiello** [comment]
Is this easier than just using the Jenkins Slack Notification Plugin?

**Comment by giorgiosironi** [comment]
All the builds use Pipeline Jenkins jobs, since those allow to define the build in the `Jenkinsfile` committed in the repository, rather than in the Jenkins UI via point-and-click. For Pipeline jobs, the plugin provides a step called [`slackSend`](https://github.com/jenkinsci/slack-plugin#pipeline-job) that can be used in place of `elifeSlack` here, but it's only a 1line difference in this diff as the hard part is to know when and what to notify more than sending the message.

**Comment by GiancarloFusiello** [comment]
> All the builds use Pipeline Jenkins jobs, since those allow to define the build in the `Jenkinsfile` committed in the repository, rather than in the Jenkins UI via point-and-click. For Pipeline jobs, the plugin provides a step called [`slackSend`](https://github.com/jenkinsci/slack-plugin#pipeline-job) that can be used in place of `elifeSlack` here, but it's only a 1line difference in this diff as the hard part is to know when and what to notify more than sending the message.

So the good thing about the point and click solution is that anyone can go into the UI and see how the jobs are configured quite easily, whereas, looking at the Jenkins file is not so intuitive. Having said that, If you're having to repeat the same configuration over and over I agree that a scripted approach is optimal.

If the Jenkins file is the most efficient approach perhaps this should be a topic for a knowledge sharing session?

**Comment by giorgiosironi** [comment]
Dissemination of knowledge about Jenkins is always a good knowledge sharing, indeed.

**Pull request merged**
